export interface Project {
  slug: string;
  title: string;
  year: string;
  location: string;
  client: string;
  funder?: string;
  amount: string;
  role: "General Contractor" | "Subcontractor";
  status: "completed" | "ongoing";
  category: "drilling" | "infrastructure";
  coordinates: [number, number];
}

export function isInternationallyFunded(project: Project): boolean {
  return !!project.funder;
}

export const projects: Project[] = [
  {
    slug: "uzgazoil-wells-drilling",
    title: "Drilling 148 Wells for Oil Drilling Rigs",
    year: "2004–2012",
    location: "Uzbekistan (multiple sites)",
    client: "UzGazOil LLC / GISSARNEFTIGAZ JV",
    amount: "$19.2M",
    role: "General Contractor",
    status: "completed",
    category: "drilling",
    coordinates: [40.7, 65.5],
  },
  {
    slug: "bayaut-vertical-drainage-reconstruction",
    title: "Reconstruction of Vertical Drainage Systems — Bayaut District",
    year: "2012–2014",
    location: "Bayaut District, Syrdarya Region",
    client: "Irrigated Land Reclamation Fund, Ministry of Finance",
    amount: "$1.7M",
    role: "General Contractor",
    status: "completed",
    category: "infrastructure",
    coordinates: [40.74, 68.35],
  },
  {
    slug: "state-security-water-supply",
    title: "Water Supply for 10 Military Units — State Security Service",
    year: "2010–2014",
    location: "Uzbekistan",
    client: "KSSB of the State Security Service of Uzbekistan",
    amount: "$1.5M",
    role: "General Contractor",
    status: "completed",
    category: "infrastructure",
    coordinates: [41.3, 64.2],
  },
  {
    slug: "vu5-guzar-reconstruction",
    title: "Reconstruction of Water Intake VU-5 — Guzar District",
    year: "2012–2013",
    location: "Guzar District, Kashkadarya Region",
    client: "Engineering Company, Single Customer Service of Kashkadarya",
    amount: "$800K",
    role: "General Contractor",
    status: "completed",
    category: "infrastructure",
    coordinates: [38.6, 66.26],
  },
  {
    slug: "vu5-yakkabag-reconstruction",
    title: "Reconstruction of Water Intake VU-5 — Yakkabag District",
    year: "2013–2014",
    location: "Yakkabag District, Kashkadarya Region",
    client: "Engineering Company, Single Customer Service of Kashkadarya",
    amount: "$1.6M",
    role: "General Contractor",
    status: "completed",
    category: "infrastructure",
    coordinates: [38.8, 66.4],
  },
  {
    slug: "syrdarya-water-supply-systems",
    title: "Construction of Water Supply Systems — Syrdarya Region",
    year: "2015–2017",
    location: "Syrdarya Region",
    client: "Engineering Company, Single Customer Service",
    amount: "$3.7M",
    role: "General Contractor",
    status: "completed",
    category: "infrastructure",
    coordinates: [40.83, 68.7],
  },
  {
    slug: "damkhodzha-pipeline-reconstruction",
    title: "Reconstruction of Damkhodzha Interregional Water Pipeline",
    year: "2015",
    location: "Uzbekistan (interregional)",
    client: "Agency UZKOMMUNHIZMAT",
    amount: "$750K",
    role: "Subcontractor",
    status: "completed",
    category: "infrastructure",
    coordinates: [40.5, 65.8],
  },
  {
    slug: "cng-wells-uztransgaz",
    title: "Drilling Wells at CNG Filling Stations",
    year: "2016",
    location: "Uzbekistan (multiple sites)",
    client: "Uztransgaz",
    amount: "$480K",
    role: "Subcontractor",
    status: "completed",
    category: "drilling",
    coordinates: [41.2, 64.9],
  },
  {
    slug: "orient-holding-water-supply",
    title: "Water Supply Systems & Well Drilling — ORIENT Production Facilities",
    year: "2017–2018",
    location: "Uzbekistan",
    client: "ORIENT Holding",
    amount: "$2.6M",
    role: "General Contractor",
    status: "completed",
    category: "infrastructure",
    coordinates: [41.29, 69.27],
  },
  {
    slug: "landscaping-wells",
    title: "Drilling Wells for Urban Landscaping",
    year: "2017",
    location: "Uzbekistan",
    client: "Housing and Communal Services Department",
    amount: "$430K",
    role: "Subcontractor",
    status: "completed",
    category: "drilling",
    coordinates: [41.3, 64.0],
  },
  {
    slug: "koshrabad-water-w31",
    title: "Improvement of Drinking Water Supply — Koshrabad District (W/3.1)",
    year: "2019–2021",
    location: "Koshrabad District, Samarkand Region",
    client: "Agency UZKOMMUNHIZMAT",
    funder:
      "OPEC Fund for International Development + Saudi Fund for Development",
    amount: "$2.88M",
    role: "General Contractor",
    status: "completed",
    category: "infrastructure",
    coordinates: [39.7, 66.95],
  },
  {
    slug: "koshrabad-water-w41",
    title: "Improvement of Drinking Water Supply — Koshrabad District (W/4.1)",
    year: "2019–2021",
    location: "Koshrabad District, Samarkand Region",
    client: "Agency UZKOMMUNHIZMAT",
    funder:
      "OPEC Fund for International Development + Saudi Fund for Development",
    amount: "$3.84M",
    role: "General Contractor",
    status: "completed",
    category: "infrastructure",
    coordinates: [39.72, 66.97],
  },
  {
    slug: "zhiydakapa-water-intake-namangan",
    title: "Reconstruction of Zhiydakapa Water Intake — Namangan Region",
    year: "2022–present",
    location: "Namangan Region",
    client: "JSC UZSUVTAMINOT",
    funder: "European Bank for Reconstruction and Development (EBRD)",
    amount: "$5.21M",
    role: "General Contractor",
    status: "ongoing",
    category: "infrastructure",
    coordinates: [40.99, 71.67],
  },
  {
    slug: "yangiyul-water-supply",
    title: "Reconstruction of Water Supply System — Yangiyul",
    year: "2023–2024",
    location: "Yangiyul City",
    client:
      "Integrated Development PIU, Ministry of Investment and Foreign Trade",
    amount: "$6.1M",
    role: "General Contractor",
    status: "completed",
    category: "infrastructure",
    coordinates: [41.11, 69.04],
  },
  {
    slug: "namangan-water-supply-phase2",
    title: "Water Supply to Northern Namangan — Phase 2",
    year: "2023–present",
    location: "Namangan City",
    client: "NAMANGAN SUV TAMINOTI",
    funder: "OPEC Fund for International Development",
    amount: "$3.48M",
    role: "General Contractor",
    status: "ongoing",
    category: "infrastructure",
    coordinates: [41.01, 71.7],
  },
];
